### ISSUE TITLE
Skapa en form för nya nyheter

### ISSUE THREAD

**Issue by alexander9907** [hallengaming/hemsida#2]
En inloggad användare ska kunna publicera nya nyheter till Nyhet-table i mysql-databasen.

**Comment by alexander9907** [comment]
@Oriaf Du fixar detta!

**Comment by alexander9907** [comment]
När du fixat detta klickar du på "Close issue"

**Comment by Oriaf** [comment]
Duly noted! Min nya enviroment är fixad så jag bör kunna starta arbeta imorgon.

**Comment by Oriaf** [comment]
Har nu comitat ändringen till loggain/nyhet.php, så jobbet borde vara klart efter att du ser över den.
